Repository StanfordLegion/realm, pull requests merged in 2025-09, with the labels that each got.

#281 Add min cuda arch to deal with kokkos compile issues
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: chore

#247 Remove cudart and hip hijacks
  CMakeLists.txt
  cmake/realm_defines.h.in
Labels: bug

#286 Add hash functions to id and some POD classes.
  src/realm.hpp
  src/realm/event.inl
  src/realm/instance.inl
  src/realm/memory.h
  src/realm/point.h
  src/realm/point.inl
  src/realm/processor.inl
  src/realm/reservation.inl
  src/realm/utils.h
  tests/CMakeLists.txt
  tests/unit_tests/hash.cc
Labels: enhancement

#289 fix the coverage target to deal with changes in add_custom_command
  cmake/CodeCoverage.cmake
  tests/CMakeLists.txt
Labels: bug

#302 Apriakhin/transpose fix 2
  src/realm/cuda/cuda_memcpy.cu
  tests/transpose_test_gpu.cc
Labels: bug

#310 Restore previous altstack when tearing down threads
  src/realm/threads.cc
Labels: bug

#313 inst: start to remove runtime_impl dependence in RegionInstance for unit testing
  src/realm/inst_impl.cc
  src/realm/inst_impl.h
  src/realm/mem_impl.cc
  src/realm/mem_impl.h
  src/realm/realm_c.cc
  tests/unit_tests/memcpy_channel_test.cc
  tests/unit_tests/sparsity_map_test.cc
  tests/unit_tests/test_common.h
  tests/unit_tests/test_common.inl
  tests/unit_tests/transfer_iterator_test.cc
Labels: chore

#320 Fix dependencies that require specifically make to build
  CMakeLists.txt
  cmake/RealmPackaging.cmake
  src/CMakeLists.txt
Labels: bug
